### PR TITLE
Front end

### PR DESCRIPTION
**Pull request by VolodymyrHoliev**
I added simple Thymeleaf template and controller.
The only thing the controller can do is to show records from `advanced_search_view` in a table.
Simple pagination is also available. For now we can move only one step forward or vice versa.
Later I will add more features. I'm thinking about adding some advanced pagination and sorting.

### CODE REVIEW

**Review by MuchosChuchos — CHANGES_REQUESTED** [review]
I have found some problems with your code:

-Your HTML page is on http://localhost:8080/12. Why?? how to navigate to that page?
-If I ran just http://localhost:8080, there is an exception `(org.thymeleaf.exceptions.TemplateProcessingException)`
-when I change on http://localhost:8080/{page} "page", I don't see the changes on the page in a browser. I mean http://localhost:8080/12 is the same as http://localhost:8080/155
-when I click on "next" or "previous", the same problem as above(The page does not change but the pathvar is increasing).
-the showing data on the page is not correct and useless. I mean that point of view is to see the different prices of meds from different pharmacies to compare it and buy cheaper. But you show data from db that can do a simple query viewer in DBeaver or in pgAdmin.

**Comment by MuchosChuchos** [comment]
You have to push to another branch, not develop

**Comment by Oleksandr-Eleks** [comment]
> You have to push to another branch, not develop

Why should he push into develop? O_o
I asked to create a branch in my repo for others to have possibility to contribute, but it should remain NOT develop.

**Comment by VolodymyrHoliev** [comment]
> I have found some problems with your code:
> 
> -Your HTML page is on http://localhost:8080/12. Why?? how to navigate to that page? -If I ran just http://localhost:8080, there is an exception `(org.thymeleaf.exceptions.TemplateProcessingException)` -when I change on [http://localhost:8080/{page}](http://localhost:8080/%7Bpage%7D) "page", I don't see the changes on the page in a browser. I mean http://localhost:8080/12 is the same as http://localhost:8080/155 -when I click on "next" or "previous", the same problem as above(The page does not change but the pathvar is increasing). -the showing data on the page is not correct and useless. I mean that point of view is to see the different prices of meds from different pharmacies to compare it and buy cheaper. But you show data from db that can do a simple query viewer in DBeaver or in pgAdmin.



> > You have to push to another branch, not develop
> 
> Why should he push into develop? O_o I asked to create a branch in my repo for others to have possibility to contribute, but it should remain NOT develop.

My bad, I'll fix it later.

**Comment by Oleksandr-Eleks** [comment]
> -the showing data on the page is not correct and useless. I mean that point of view is to see the different prices of meds from different pharmacies to compare it and buy cheaper. But you show data from db that can do a simple query viewer in DBeaver or in pgAdmin.

That's enough for the start. We should be able to see at least something before deployment! ;)

**Comment by Oleksandr-Eleks** [comment]
Please rebase Your branch correctly.

**Comment by VolodymyrHoliev** [comment]
I know that it's far from being good, but since I should spend more time at work I wasn't sure if I could go it well and on time. Therefore, I pushed this as is. I'll try to make it better as soon as I can. Consider this as a prototype, not the final version.

**Comment by Oleksandr-Eleks** [comment]
@VolodymyrHoliev 
@MuchosChuchos 
@Anna-Kudiakova 
@kolyaratishin 
@MariamnaKh 
@zyoneal 
@Dichik 
@FedenkoMykhailo 
@SofiiaOlenyn 
@ksanderGit 
@ritalinch 
@ChernoVl 
@Zond47 
and others... :)
You may merge it into `front_end` branch of main repo and add needed modifications.

**Comment by MuchosChuchos** [comment]
> > You have to push to another branch, not develop
> 
> Why should he push into develop? O_o I asked to create a branch in my repo for others to have possibility to contribute, but it should remain NOT develop.

he has pushed to develop. I told him to push to the front_end

**Comment by MuchosChuchos** [comment]
so many commits here. try to use interactive rebase and then while pushing set the -f

**Comment by MuchosChuchos** [comment]
> 

not problem. it's okay. we're just studying

**Comment by Oleksandr-Eleks** [comment]
> so many commits here. try to use interactive rebase and then while pushing set the -f

This is not the case for interactive rebase. This branch should be rebased properly.

**Review by MariamnaKh — APPROVED** [review]

**Pull request closed without merging**
